# Generated by Django 4.1.1 on 2022-10-18 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_country_state_city'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('cpf', models.CharField(default='', max_length=20)),
                ('cnpj', models.CharField(default='', max_length=20)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=60)),
                ('cep', models.CharField(default='', max_length=20)),
                ('street', models.CharField(default='', max_length=50)),
                ('district', models.CharField(default='', max_length=50)),
                ('num', models.CharField(default='', max_length=20)),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='default.city')),
            ],
        ),
    ]
