# Generated by Django 4.1.1 on 2022-10-19 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_state_country'),
        ('register', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_f_j', models.IntegerField(choices=[(1, 'Física'), (2, 'Jurídica')])),
                ('person_type', models.IntegerField(choices=[(1, 'Transportador'), (2, 'Cliente'), (3, 'Fornecedor')])),
                ('name', models.CharField(default='', max_length=80)),
                ('corporate_name', models.CharField(default='', max_length=80)),
                ('fantasy_name', models.CharField(default='', max_length=80)),
                ('cpf', models.CharField(default='', max_length=20)),
                ('cnpj', models.CharField(default='', max_length=20)),
                ('ie', models.CharField(default='', max_length=20)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=60)),
                ('cep', models.CharField(default='', max_length=20)),
                ('street', models.CharField(default='', max_length=50)),
                ('district', models.CharField(default='', max_length=50)),
                ('num', models.CharField(default='', max_length=20)),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='default.city')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
