# Generated by Django 4.1.1 on 2022-10-19 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_state_country'),
        ('register', '0003_partner_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='default.company'),
            preserve_default=False,
        ),
    ]
