# Generated by Django 4.1.1 on 2022-10-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_partner_corporate_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('company', 'name'), 'verbose_name': 'Parceria', 'verbose_name_plural': 'Parcerias'},
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='corporate_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='partner',
            name='fantasy_name',
            field=models.CharField(default='', max_length=80),
        ),
    ]
