# Generated by Django 4.1.1 on 2022-10-20 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_state_country'),
        ('register', '0007_alter_partner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='company_worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='default.companyworker'),
            preserve_default=False,
        ),
    ]
