# Generated by Django 4.1.1 on 2022-10-20 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_state_country'),
        ('register', '0009_alter_partner_cnpj_alter_partner_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='city',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='default.city'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='company',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='default.company'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='company_worker',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='default.companyworker'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='fantasy_name',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='ie',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='person_f_j',
            field=models.IntegerField(choices=[(1, 'Física'), (2, 'Jurídica')], default='1'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='person_type',
            field=models.IntegerField(choices=[(1, 'Cliente'), (2, 'Fornecedor'), (3, 'Transportador')], default='1'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
