# Generated by Django 4.0.4 on 2022-10-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_rename_fantasy_name_partner_fantasy'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='rg',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
