# Generated by Django 4.1.1 on 2022-10-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_country_state_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('created',), 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('created',), 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('created',), 'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
        migrations.AddField(
            model_name='city',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2022-09-18 14:49:36.787404-04'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='country',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2022-09-18 14:49:36.787404-04'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='state',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2022-09-18 14:49:36.787404-04'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
